GET {{test_host}}/dishes/favorite
Accept: application/json

SNAPSHOT
status: 200

content-type: application/json
correlation-id: {{_ : guid }}
content-length: 70
date: {{ _ : _}}

{
  "id": {{_ : guid}},
  "name": "Beef Wellington"
}