GET {{test_host}}/guid
Accept: application/json

SNAPSHOT
status: 200

content-length: 45
content-type: application/json
correlation-id: {{_: guid}}
date: {{_: timestamp("%a, %d %b %Y %H:%M:%S %Z")}}

{
  "id": {{_: guid}}
}