GET {{test_host}}/guid
Accept: application/json

SNAPSHOT
status: 200

content-length: 45
content-type: application/json
correlation-id: *guid*
date: *timestamp("%a, %d %b %Y %H:%M:%S %Z")*

{
  "id": *guid*
}