@id = gen(guid)

POST {{test_host}}/item/{{id}}
Accept: application/json
Content-type: application/json

SNAPSHOT
status: 200

content-length: 59
content-type: application/json
date: {{_:timestamp("%a, %d %b %Y %H:%M:%S %Z"):"Thu, 15 May 2025 11:26:57 GMT"}}
location: /item/{{id}}

{
  "id": {{_:guid:"b1e28032-7150-4c15-b0c9-fc2277293e3f"}},
  "name": "Echo"
}