include-headers: false

POST https://localhost:50001/sign-in

SNAPSHOT:
status: 200

null

###

POST https://localhost:50001/api/items
Content-Type: application/json; charset=utf-8

{
  "text": "Something"
}

SNAPSHOT:
status: 201

content-type: application/json; charset=utf-8
date: _
server: Kestrel
location: _
transfer-encoding: chunked

{
  "id": _
}

###

@location = {{previous.headers["location"]}}

DELETE https://localhost:50001{{location}}
Content-Type: application/json; charset=utf-8

SNAPSHOT:
status: 204

date: _
server: Kestrel

null

###

POST https://localhost:50001{{location}}/complete
Content-Type: application/json; charset=utf-8

SNAPSHOT:
status: 404

content-type: application/problem+json
date: _
server: Kestrel
transfer-encoding: chunked

{
  "type": "https://tools.ietf.org/html/rfc9110#section-15.5.5",
  "title": "Not Found",
  "status": 404,
  "detail": "Item not found."
}