include-headers: false

@path = "sign-in"
POST https://localhost:50001/{{path}}

SNAPSHOT:
status: 200

null

###

POST https://localhost:50001/api/items
Content-Type: application/json; charset=utf-8

{
  "text": ""
}

SNAPSHOT:
status: 400

content-type: application/problem+json
date: _
server: Kestrel
transfer-encoding: chunked

{
  "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
  "title": "Bad Request",
  "status": 400,
  "detail": "No item text specified."
}