@degrees = 2

POST https://localhost:7028/measurement
Accept: application/json
Content-Type: application/json

{
  "degrees": {{degrees}}
}

SNAPSHOT
status: 200

content-type: application/json; charset=utf-8
date: _
server: Kestrel
transfer-encoding: chunked

{
  "date": _,
  "temperatureC": 2,
  "summary": _,
  "temperatureF": 35
}