@name = "John"
@user = "doe"
@guid = "f849146f-ceaa-49e9-8d41-977fcb1e830d"

POST https://webhook.site/{{guid}}
Authorization: Basic {{user}} 12345678
Content-Type: application/json

{
  "details": "Hello {{name}}!"
}

SNAPSHOT
status: 200

server: nginx
content-type: text/html; charset=UTF-8
transfer-encoding: chunked
x-request-id: _
x-token-id: _
cache-control: no-cache, private
date: timestamp("%a, %d %b %Y %H:%M:%S GMT")

null